APP_ADDR1: 192.180.10.79:30574
APP_ADDR2: 192.180.10.79:32285
CCE_PASSWORD: 1qaz@WSX
CLUSTER_ID: E5E2FA1F-C6EB-4E97-A214-E04D0D0A
CLUSTER_NAME: auto.kaas
HOST: 172.25.48.147
PACKAGE_NAME_OF_HELM: auto-helm-pwtzb
PACKAGE_NAME_OF_IMAGE: autouykw
PACKAGE_NAME_OF_JAR: auto-jar-yzfve
PACKAGE_NAME_OF_ROLLBACK_FROM_JAR: auto-jar-vmpso
PACKAGE_NAME_OF_UPGRAGE_FROM_JAR: auto-jar-vmpso
PACKAGE_NAME_OF_WAR: auto-war-irmkf
PACKAGE_NAME_OF_WEB: auto-web-gycev
PACKAGE_PATH_OF_CCE_LINUX: /testplat/images/autotest-cce.tar
PACKAGE_PATH_OF_CCE_WINDOWS: E:\2023\01 images\autotest-cce.tar
PACKAGE_PATH_OF_HELM: E:\2023\01 images\helm20222\appa-x86.zip
PACKAGE_PATH_OF_HELM_LINUX: /testplat/images/helm20222/appa.zip
PACKAGE_PATH_OF_HELM_WINDOWS: E:\2023\01 images\helm20222\appa-x86.zip
PACKAGE_PATH_OF_IMAGE: E:\2023\01 images\container8080\mytomcat.tar
PACKAGE_PATH_OF_IMAGE_LINUX: /testplat/images/container8080/mytomcat.tar
PACKAGE_PATH_OF_IMAGE_WINDOWS: E:\2023\01 images\container8080\mytomcat.tar
PACKAGE_PATH_OF_JAR: E:\2023\01 images\jar_with_springcloud20111\application-A-V1.0.0-exec.jar
PACKAGE_PATH_OF_JAR_LINUX: /testplat/images/jar_with_springcloud20111/application-A-V1.0.0-exec.jar
PACKAGE_PATH_OF_JAR_WINDOWS: E:\2023\01 images\jar_with_springcloud20111\application-A-V1.0.0-exec.jar
PACKAGE_PATH_OF_ROLLBACK_FROM_JAR: E:\2023\01 images\jar20333\application-A-V2.0.0-exec.jar
PACKAGE_PATH_OF_ROLLBACK_FROM_JAR_LINUX: /testplat/images/jar20333/application-A-V2.0.0-exec.jar
PACKAGE_PATH_OF_ROLLBACK_FROM_JAR_WINDOWS: E:\2023\01 images\jar20333\application-A-V2.0.0-exec.jar
PACKAGE_PATH_OF_TECHOPS_LINUX: /testplat/images/jar_with_techops_sql/sw-dev-test.jar
PACKAGE_PATH_OF_UPGRAGE_FROM_JAR: E:\2023\01 images\jar20333\application-A-V1.0.0-exec.jar
PACKAGE_PATH_OF_UPGRAGE_FROM_JAR_LINUX: /testplat/images/jar20333/application-A-V1.0.0-exec.jar
PACKAGE_PATH_OF_UPGRAGE_FROM_JAR_WINDOWS: E:\2023\01 images\jar20333\application-A-V1.0.0-exec.jar
PACKAGE_PATH_OF_WAR: E:\2023\01 images\war8080\demo-v1.war
PACKAGE_PATH_OF_WAR_LINUX: /testplat/images/war8080/demo-v1.war
PACKAGE_PATH_OF_WAR_WINDOWS: E:\2023\01 images\war8080\demo-v1.war
PACKAGE_PATH_OF_WEB: "E:\\2023\\01 images\\front80\\\u524D\u7AEF\u5305\\vue-demo-three.zip"
PACKAGE_PATH_OF_WEB_LINUX: /testplat/images/front80/vue-demo-three.zip
PACKAGE_PATH_OF_WEB_WINDOWS: "E:\\2023\\01 images\\front80\\\u524D\u7AEF\u5305\\vue-demo-three.zip"
PACKAGE_VERSION_OF_HELM: MgUcu
PACKAGE_VERSION_OF_IMAGE: v1
PACKAGE_VERSION_OF_JAR: sgYDa
PACKAGE_VERSION_OF_ROLLBACK_FROM_JAR: wYAfv
PACKAGE_VERSION_OF_UPGRAGE_FROM_JAR: NHSAr
PACKAGE_VERSION_OF_WAR: VZ3KI
PACKAGE_VERSION_OF_WEB: kWjmC
PASSWORD: Passw0rd@_
PORT: '443'
PROJECT_NAME: root
PROJ_ADMIN: pro_admin
PROJ_ADMIN_PACKAGE_NAME_OF_HELM: auto-helm-wiksc
PROJ_ADMIN_PACKAGE_NAME_OF_JAR: auto-jar-ojkgl
PROJ_ADMIN_PACKAGE_NAME_OF_ROLLBACK_FROM_JAR: auto-jar-pgzqt
PROJ_ADMIN_PACKAGE_NAME_OF_UPGRAGE_FROM_JAR: auto-jar-pgzqt
PROJ_ADMIN_PACKAGE_NAME_OF_WAR: auto-war-yvpdl
PROJ_ADMIN_PACKAGE_NAME_OF_WEB: auto-web-njppr
PROJ_ADMIN_PACKAGE_VERSION_OF_HELM: nAysG
PROJ_ADMIN_PACKAGE_VERSION_OF_JAR: Qzqun
PROJ_ADMIN_PACKAGE_VERSION_OF_ROLLBACK_FROM_JAR: Qzkpg
PROJ_ADMIN_PACKAGE_VERSION_OF_UPGRAGE_FROM_JAR: pKLfg
PROJ_ADMIN_PACKAGE_VERSION_OF_WAR: DULaP
PROJ_ADMIN_PACKAGE_VERSION_OF_WEB: fhWSp
PROJ_USER: pro_user
PUBLIC_KEY: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCbPqaFZ0lgebihxCw5wzjkahPKr6ZI2JNTHbHDnNbOn3Cif6GgnMBr44MhQCRPQTF2FgcxBbn3u7eGcEPMT6OZqcLzcmiMCUQRJ2MUbFI+E1vI1f+iuCQ2w8XZhRoRrmb7wBA0L63gnSwXRkJD0baL5zqlQhpSKfSH0t3opAoahwIDAQAB
TAG: autonhtaij
USERNAME: admin
cce_image: E:\2023\01 images\autotest-cce.tar
